// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5PlfM17B6MgsxqP2onHCdL0j1lwe4e8E',
    appId: '1:222903535503:web:c51cf3d785dc8327486dfa',
    messagingSenderId: '222903535503',
    projectId: 'slitems',
    authDomain: 'slitems.firebaseapp.com',
    storageBucket: 'slitems.appspot.com',
    measurementId: 'G-9W2SHSEBKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-3pD65Dy26PkmqEQfR3gGlA6ULOrgqI',
    appId: '1:222903535503:android:63a881b969f5fe6f486dfa',
    messagingSenderId: '222903535503',
    projectId: 'slitems',
    storageBucket: 'slitems.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgjeGzsq6ELts1dzBm7Beb5T8OqHg6owk',
    appId: '1:222903535503:ios:7acafe5800706f7d486dfa',
    messagingSenderId: '222903535503',
    projectId: 'slitems',
    storageBucket: 'slitems.appspot.com',
    iosClientId: '222903535503-u4dc10mhsfvh4rt7qflqiap39q6ibjun.apps.googleusercontent.com',
    iosBundleId: 'com.example.slitem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgjeGzsq6ELts1dzBm7Beb5T8OqHg6owk',
    appId: '1:222903535503:ios:7acafe5800706f7d486dfa',
    messagingSenderId: '222903535503',
    projectId: 'slitems',
    storageBucket: 'slitems.appspot.com',
    iosClientId: '222903535503-u4dc10mhsfvh4rt7qflqiap39q6ibjun.apps.googleusercontent.com',
    iosBundleId: 'com.example.slitem',
  );
}
